config/routes.rb
Klickrr::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'spa#index'

  get "tracking/:token" => 'spa#tracking', :as => 'tracking_pixel'

  get "json/service_conf" => "spa#service_conf"
  post "save_service_conf" => "spa#save_service_conf"
  post "delete_service_conf" => "spa#delete_service_conf"

  get "services/list/active" => "spa#active_services"
  get "list/services/:list_id" => "spa#active_list_services"
  post "list/services/update" => "spa#update_list_services"

  post "list/upload" => "spa#upload_list"
  post "list/create" => "spa#create_list"
  post "list/update" => "spa#update_list"
  post "list/destroy" => "spa#destroy_list"
  post "list/domain/save" => "spa#save_list_domain"
  post "list/sender_email/save" => "spa#save_list_sender_email"
  post "list/sender_name/save" => "spa#save_list_sender_name"
  get "lists/list" => "spa#lists_list"
  get "lists/total_pages" => "spa#lists_total_pages"
  get "list" => "spa#get_list"
  get "lists/collection" => "spa#lists_collection"
  get "list/:list_id/broadcasts" => "spa#broadcasts_collection"

  get "broadcast/list" => "spa#broadcast_list"
  get "broadcast/total_pages" => "spa#broadcast_total_pages"
  post "broadcast/create" => "spa#create_broadcast"
  post "broadcast/clone" => "spa#clone_broadcast"
  post "broadcast/update" => "spa#update_broadcast"
  post "broadcast/update_and_send" => "spa#update_and_send_broadcast"
  post "broadcast/segments" => "spa#segment_broadcast"
  delete "broadcast/delete/:id" => "spa#delete_broadcast"
  delete "broadcast/segments/delete" => "spa#delete_broadcast_segments"
  post "/broadcast/save_test_message" => "spa#save_test_message"
  get "list/:list_id/check_test_broadcast" => "spa#check_test_broadcast"
  post "/broadcast/send_test_message" => "spa#send_test_broadcast"
  post "/broadcast/send_test_message_from_broadcast" => "spa#send_test_message_from_broadcast"
  get '/broadcasts/status/:id' => 'spa#broadcast_status'
  get '/broadcasts/:id/unschedule' => 'spa#broadcast_unschedule'
  get 'broadcast' => 'spa#get_broadcast'
  post 'broadcast/services/update' => 'spa#update_broadcast_services'

  get "followup/list" => "spa#followup_list"
  get "followup/load/:id", to: "spa#followup_load"
  get "followup/total_pages" => "spa#followup_total_pages"
  post "followup/save" => "spa#save_followup"
  post "followup/clone" => "spa#clone_followup"
  post "followup/update" => "spa#update_followup"
  delete "followup/delete/:id" => "spa#delete_followup"
  get "followup/triggers_by_scope" => "spa#followup_triggers_by_scope"
  post "followup/state/toggle", to: "spa#followup_state_toggle"
  get 'followup' => 'spa#get_followup'
  post 'followup/services/update' => 'spa#update_followup_services'
  get 'followups', to: 'spa#get_followups'

  get "analytics/data" => "spa#generate_analytics"
  post "analytics/data" => "spa#generate_analytics"

  post "analytics/get_pixel" => "spa#get_pixel"

  get "payload" => "spa#aggregate_payload"
  post "payload" => "spa#aggregate_payload"

  get "subscribe/:list_group_id" => "outside#subscribe"
  get "unsubscribe/me/:tracking_code" => "outside#unsubscribe_me"
  get "list/:list_id/subscribers" => "spa#subscriber_preview"
  get "list/:list_id/subscribers/columns" => "spa#subscriber_columns"
  post "list/search" => "spa#subscriber_search"
  get "list/subscribers/:list_id/export" => "spa#subscriber_csv_export"
  post "list/subscribers/count" => "spa#list_subscriber_count"
  post "list/delete/contact" => "spa#remove_subscriber_from_list"
  get "list/combos", to: "spa#list_combos"
  get "list/segments/:list_id", to: "spa#list_segments"
  post "list/segments/save", to: "spa#save_list_segments"
  post "list/fields", to: "spa#fields_list"
  get "list/:list_id/add_new_subscriber", to: "spa#add_new_subscriber"
  post "list/:list_id/save_subscriber", to: "spa#save_subscriber"
  post "list/:list_id/subscriber_email_validate", to: "spa#subscriber_email_validate"
  post "list/update_subscriber/:id", to: "spa#update_subscriber"
  post "dashboard/list/analytics", to: "analytics#list_analytics"
  get "dashboard/list/analytics", to: "analytics#list_analytics"
  post "analytics/broadcast/count", to: "analytics#broadcast_send_count"
  get "analytics/broadcast/:broadcast_id/count", to: "analytics#broadcast_send_count"

  get "lnks/:tracking_code" => "mail#click_tracking"

  post "partners/zaxaa" => "accounts#zaxaa_zpn"
  match "user/create" => "accounts#spawn_user", via: [:options]
  post "user/create" => "accounts#spawn_user"

  post "smtp/send" => "mail#send_smtp"
  post "api/send" => "mail#send_api"
  post "api/test" => "mail#test_service"
  post "broadcast/send" => "spa#create_and_send_broadcast"
  post "followup/test/send" => "mail#send_message"
  get "followup/send/:id" => "mail#send_followup"
  post "mail/raw" => "mail#raw_mail"
  get "mail/progress/:message_id/:message_type" => "mail#mailing_progress"

  post "feedback/save" => "spa#save_feedback"

  post "webform/process/:form_code" => "spa#process_submitted_webform"

  post "webform/save" => "spa#save_webform"
  post "webform/delete" => "spa#destroy_webform"
  post "webform/clone" => "spa#clone_webform"
  get "webform/:list_field_group_id/load" => "spa#load_webform"
  get "webform/list" => "spa#webform_list"
  get "webform/total_pages" => "spa#webform_total_pages"
  get "list/webforms" => "spa#webforms_for_list"

  post "webform/:list_field_group_id/save" => "spa#save_webform"

  get "webform/template/:template_name" => "spa#load_form_template"
  get "list/:list_id/collections" => "spa#list_collections"

  get "tutorials", to: 'support#tutorials'

  get "open" => "mail#open_pixel"

  post "webhooks/incoming" => "webhooks#incoming"

  resources :services_users, only: :update
  resources :user_services_settings, only: [] do
    put :update, on: :collection
  end
end

app/helpers/spa_helper.rb
module SpaHelper
  def leads_stats(list_id)
    stats = {}

    stats["today"] = {}
    stats["7days"] = {}
    stats["30days"] = {}
    stats["90days"] = {}
    stats["year"] = {}
    stats["alltime"] = {}

    list_ids = nil

    # Get the list(s) to display data for.
    if list_id.blank?
      list_ids = current_user.lists.all.pluck(:id).join(", ")
      list_ids = 'NULL' if list_ids.blank?
    else
      list_ids = list_id
    end

    unless list_ids.blank?
      # Define the vars we are about to populate.
      creation_date = nil
      updated_date = nil

      stats.each do |key, data|
        case key
          when "today"
            creation_date = "created_at::DATE = CURRENT_DATE"
            updated_date = "updated_at::DATE = CURRENT_DATE"
            interval = Time.now
          when "7days"
            creation_date = "created_at::DATE BETWEEN CURRENT_DATE - interval '7 days' AND CURRENT_DATE"
            updated_date = "updated_at::DATE BETWEEN CURRENT_DATE - interval '7 days' AND CURRENT_DATE"
            interval = Time.now - 7.days
          when "30days"
            creation_date = "created_at::DATE BETWEEN CURRENT_DATE - interval '30 days' AND CURRENT_DATE"
            updated_date = "updated_at::DATE BETWEEN CURRENT_DATE - interval '30 days' AND CURRENT_DATE"
            interval = Time.now - 30.days
          when "90days"
            creation_date = "created_at::DATE BETWEEN CURRENT_DATE - interval '90 days' AND CURRENT_DATE"
            updated_date = "updated_at::DATE BETWEEN CURRENT_DATE - interval '90 days' AND CURRENT_DATE"
            interval = Time.now - 90.days
          when "year"
            creation_date = "created_at::DATE BETWEEN CURRENT_DATE - interval '1 year' AND CURRENT_DATE"
            updated_date = "updated_at::DATE BETWEEN CURRENT_DATE - interval '1 year' AND CURRENT_DATE"
            interval = Time.now - 1.year
        end

        unless key === "alltime"
          # Since the SQL string contains single ticks, we need to escape our single tick creation_date.
          new_leads_creation_date = creation_date.gsub("'", "''")

          stats["#{key}"]["new_leads"] = List.find_by_sql("SELECT COUNT(set_id) AS rows from crosstab('SELECT set_id, label, field_value FROM list_fields LEFT OUTER JOIN (SELECT * FROM list_values WHERE #{new_leads_creation_date}) AS list_values_table ON (list_values_table.list_field_id = list_fields.id) WHERE list_id IN (#{list_ids}) ORDER BY list_values_table.id LIMIT 50') AS ct(set_id int, first_name text, last_name text, email text);")[0].rows;
        else
          stats["#{key}"]["new_leads"] = List.find_by_sql("SELECT COUNT(set_id) AS rows from crosstab('SELECT set_id, label, field_value FROM list_fields LEFT OUTER JOIN (SELECT * FROM list_values) AS list_values_table ON (list_values_table.list_field_id = list_fields.id) WHERE list_id IN (#{list_ids}) ORDER BY list_values_table.id LIMIT 50') AS ct(set_id int, first_name text, last_name text, email text);")[0].rows;
        end

        ####################################
        ## Unsubscribes
        ####################################
        unsub_count = 0
        # byebug
        unless current_user.sent_mails.blank?
          unsubs = current_user.sent_mails.where(["#{updated_date} AND unsubscribed IS NOT NULL"]).pluck(:unsubscribed)

          unsubs.each do |unsub|
            # Unsubscribed should never be null, but just in case...
            unless unsub.blank?
              if key === "today"
                if unsub.to_datetime.strftime('%Y-%m-%d') === Date.today
                  unsub_count += 1
                end
              elsif key === "alltime"
                unsub_count += 1
              else
                if unsub.to_datetime.strftime('%Y-%m-%d') >= interval
                  unsub_count += 1
                end
              end
            end
          end
        end

        stats["#{key}"]["unsubscribes"] = unsub_count
        ####################################
        ## End unsubscribes
        ####################################


        ####################################
        ## Opens
        ####################################
        opens = current_user.sent_mails.where(["#{updated_date} AND opened IS NOT NULL"]).pluck(:opened)
        open_count = 0
        opens.each do |o|
          # Open should never be null, but just in case...
          unless o.blank?
            if (o[0] === "[" && o[6..7] === "=>") || o[2] === ":"
              o = eval(o)
            elsif o[0] === "{" || (o[0..1] === "[{" && o[7] === ":")
              o = JSON.parse(o)
            end

            # Check to see if this is just a date string or array of hashes (legacy support).
            unless o.class === "String"
              opened_at = o[0][:opened_at]
            else
              opened_at = o
            end

            if key === "today"
              if opened_at.to_datetime.strftime('%Y-%m-%d') === Date.today
                open_count += 1
              end
            elsif key === "alltime"
              open_count += 1
            else
              unless opened_at.blank?
                if opened_at.to_datetime.strftime('%Y-%m-%d') >= interval
                  open_count += 1
                end
              end
            end
          end
        end

        stats["#{key}"]["opens"] = open_count
        ####################################
        ## End Opens
        ####################################

        ####################################
        ## Clicks
        ####################################
        clicks = current_user.sent_mails.where(["#{updated_date} AND clicks IS NOT NULL"]).pluck(:clicks)
        click_count = 0

        clicks.each do |click|
          # Clicks should never be null, but just in case...
          unless click.blank?
            if (click[0] === "[" && click[6..7] === "=>") || click[2] === ":"
              click_arr = eval(click)
            elsif click[0] === "{" || (click[0..1] === "[{" && click[7] === ":")
              click_arr = JSON.parse(click)
            end

            # In case there are multiple clicks for this, iterate through all.
            click_arr.each do |clk|
              # Check if we have a click date (legacy support)
              if (clk.include? "clicked_at")# || (clk.has_key?(:clicked_at)) || (clk.has_key?("clicked_at"))
                # Check to see if this is just a date string or array of hashes (legacy support).
                unless clk.is_a? String

                  puts "clk: #{clk}"
                  if clk.is_a? Hash
                    clicked_at = if clk.keys[0].is_a?(Symbol)
                                   clk[:clicked_at]
                                 else
                                   clk["clicked_at"]
                                 end
                    #end
                  else#if clk.is_a? Array
                    clicked_at = clk[1]
                  end
                else
                  clicked_at = clk
                end

                if key === "today"
                  if clicked_at.to_datetime.strftime('%Y-%m-%d') === Date.today
                    click_count += 1
                  end
                elsif key === "alltime"
                  click_count += 1
                else
                  unless clicked_at.blank?
                    if clicked_at.to_datetime.strftime('%Y-%m-%d') >= interval.to_datetime.strftime('%Y-%m-%d')
                      click_count += 1
                    end
                  end
                end
              end
            end
          end
        end

        stats["#{key}"]["clicks"] = click_count
        ####################################
        ## End clicks
        ####################################
      end

      # Get the total number of leads
      stats["total_leads"] = List.find_by_sql("SELECT COUNT(DISTINCT set_id) AS row_count FROM list_values WHERE list_field_group_id IN (SELECT ID FROM list_field_groups WHERE list_id IN (#{list_ids}))")[0].row_count;

    end

    return stats
  end
end

app/views/spa/index.html.erb
<!--div class="alert alert-danger" role="alert">NOTE: While scalability upgrades are in progress, Klickrr is currently NOT sending messages.</div-->
<div id="loader">
  <i class="fa fa-spinner fa-spin"></i><span id="loader_text">&nbsp;loading...</span>
</div>
<!--div class="row"-->
<!--div style="padding-top: 80px;"> </div-->
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--a class="navbar-brand" href="#">Klickrr</a-->
      <a class="navbar-brand" href="#"><%= image_tag "Klickrr logo.png", :height => 25 %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <div class="form-group" style="position: relative; padding-top: 10px;">
            <select name="master_lists_sel" id="master_lists_sel" class="form-control input-sm sel-lists" onChange="ChangeTitle(this)"></select>
          </div>
        </li>
        <li><%= link_to "Tutorials", tutorials_path %></li>
        <!--<li><a href="#" data-toggle="modal" data-target="#mod_tutorials_and_support">Tutorials</a></li>-->
        <li><a href="#" data-toggle="modal" data-target="#mod_tutorials_and_support">Support</a></li>
        <% if user_signed_in? %>
        <li role="presentation" class="dropdown">
              <a data-toggle="dropdown" href="#" class="dropdown-toggle"><%= current_user.email %>&nbsp;<span class="caret"></strong></a>
        <div class="dropdown-menu dropdown-menu-right" style="padding: 15px; padding-bottom: 0px;">
                <!-- Profile editor -->
                <div class="container" style="padding-top: 30px; width: 800px;">
                  <h1 class="page-header">Edit Profile</h1>
                  <div class="row">
                    <!-- edit form column -->
                    <div class="col-md-12 col-sm-12 col-xs-12 personal-info">
                      <!--div class="alert alert-info alert-dismissable">
                        <a class="panel-close close" data-dismiss="alert">×</a>
                        <i class="fa fa-sitemap"></i>
                        <span class="lead">This feature is in progress and will be available soon after the beta launch.</span>
                      </div-->
                      <h3>Personal info</h3>
                      <%= render "devise/registrations/edit" %>
                      <!-- <form class="form-horizontal" role="form">
                        <div class="form-group">
                          <label class="col-lg-3 control-label">First name:</label>
                          <div class="col-lg-8">
                            <input class="form-control" value="<%= current_user.first_name %>" type="text" />
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="col-lg-3 control-label">Last name:</label>
                          <div class="col-lg-8">
                            <input class="form-control" value="<%= current_user.last_name %>" type="text" />
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="col-lg-3 control-label">Email:</label>
                          <div class="col-lg-8">
                            <input class="form-control" value="<%= current_user.email %>" type="text">
                          </div>
                        </div>
                        <h3>Change Password</h3>
                        <div class="form-group">
                          <label class="col-md-3 control-label">New Password:</label>
                          <div class="col-md-8">
                            <input class="form-control" type="password" />
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="col-md-3 control-label">Confirm new assword:</label>
                          <div class="col-md-8">
                            <input class="form-control" type="password" />
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="col-md-3 control-label"></label>
                          <div class="col-md-8">
                            <input class="btn btn-primary" value="Save Changes" type="button">
                            <span></span>
                            <input class="btn btn-default" value="Cancel" type="reset">
                          </div>
                        </div>
                      </form> -->
                    </div>
                  </div>
                </div>
                <!-- End profile editor -->
              </div>
            </li>
        <% end %>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <!--li style="vertical-align: middle; margin-top: 10px;"><i class="fa fa-cog" style="font-size: 2.0em;"></i></li-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="row">
  <div class="col-md-12">
    <div role="tabpanel">
      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist" id="function_tabs">
        <li role="presentation" class="active"><a href="#dashboard" aria-controls="dashboard" role="tab" data-toggle="tab"><i class="fa fa-tachometer"></i> Dashboard</a></li>
        <li role="presentation"><a href="#services" aria-controls="home" role="tab" data-toggle="tab"><i class="fa fa-database"></i>
          Services</a></li>
        <li role="presentation"><a href="#lists_list" aria-controls="profile" role="tab" data-toggle="tab"><i class="fa fa-envelope"></i>
          Lists</a></li>
        <li role="presentation"><a href="#broadcast_list" aria-controls="messages" role="tab" data-toggle="tab"><i class="fa fa-bullhorn"></i>
          Broadcast</a></li>
        <li role="presentation"><a href="#followup_list" aria-controls="settings" role="tab" data-toggle="tab"><i class="fa fa-comment"></i>
          Follow Up</a></li>
        <li role="presentation"><a href="#webform_list" aria-controls="settings" role="tab" data-toggle="tab"><i class="fa fa-code"></i>
          Web Form</a></li>
        <li role="presentation"><a href="#analytics" aria-controls="settings" role="tab" data-toggle="tab"><i class="fa fa-bar-chart"></i>
          Analytics</a></li>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">

        <!-- Begin Dashboard tab. -->
        <%= render "partials/dashboard" %>
        <!-- End Dashboard tab. -->

        <!-- Begin Servers tab. -->
        <%= render "partials/service" %>
        <!-- End Servers tab. -->

        <!-- Begin Lists tab. -->
        <%= render "partials/lists_list" %>

        <%= render "partials/list" %>
        <%= render "partials/list_combo" %>
        <!-- End Lists tab. -->

        <!-- Begin Broadcast tab. -->
        <%= render "partials/broadcast_list" %>
        <%= render "partials/broadcast" %>
        <!-- End Broadcast tab. -->

        <!-- Begin Follow up tab. -->
        <%= render "partials/followup_list" %>

        <%= render "partials/followup" %>
        <!-- End Follow up tab. -->

        <!-- Begin Web form tab. -->
        <%= render "partials/webform_list" %>
        <%= render "partials/webform" %>
        <!-- End Web form tab. -->

        <!-- Begin Analytics tab. -->
        <%= render "partials/analytics" %>
        <!-- End Analytics tab. -->
      </div>
    </div>
  </div>
</div>
<!--/div-->

<!-- Begin modals. -->
<%= render "partials/modals" %>
<!-- End modals. -->

<%= hidden_field_tag "uid", current_user.id %>